# Generated by Django 5.0.6 on 2026-06-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='hrv_rmssd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='sleep_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
