# Generated by Django 5.0.6 on 2026-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_bodymeasurement_hrv_rmssd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='neck_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Neck circumference in cm — used for the U.S. Navy body-fat formula.', max_digits=5, null=True),
        ),
    ]
