# Generated by Django 5.0.6 on 2026-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_bodymeasurement_neck_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymeasurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
