# Generated by Django 5.0.6 on 2026-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='reports_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
