# Generated by Django 5.0.6 on 2026-06-12 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('serving_size', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('serving_unit', models.CharField(default='g', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sugar_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('consumed_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx'),
        ),
    ]
