# Generated by Django 5.0.6 on 2026-06-23 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'consumed_at'], name='meal_user_consumed_at_idx'),
        ),
    ]
