# Generated by Django 5.0.6 on 2026-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('strava', 'Strava'), ('intervals', 'Intervals.icu')], max_length=32),
        ),
    ]
