# Generated by Django 5.0.6 on 2026-06-12 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight loss'), ('weight_gain', 'Weight gain'), ('strength', 'Strength PR'), ('endurance', 'Endurance'), ('workouts_per_week', 'Workouts per week'), ('calories', 'Daily calorie target'), ('custom', 'Custom')], max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('starting_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(blank=True, help_text='kg, lb, reps, min, etc.', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
