# Generated by Django 5.0.6 on 2026-06-23 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_options_goal_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goal_user_status_idx'),
        ),
    ]
