# Generated by Django 5.0.6 on 2026-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='kind',
            field=models.CharField(choices=[('workout_count', 'Total workouts'), ('streak_days', 'Consecutive day streak'), ('volume_total', 'Total lifting volume (kg)'), ('workout_minutes', 'Total workout minutes'), ('calorie_burn', 'Total calories burned'), ('distance_km', 'Total distance covered (km)'), ('early_bird', 'Workouts started before 7 am'), ('night_owl', 'Workouts started at 9 pm or later'), ('goals_completed', 'Goals marked achieved')], max_length=30),
        ),
    ]
