# Generated by Django 5.0.6 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_avg_hr_bpm_workout_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='routine',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
