# Generated by Django 5.0.6 on 2026-06-23 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_routine_options_routine_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'status', '-started_at'], name='workout_user_status_date_idx'),
        ),
    ]
