# Generated by Django 5.0.6 on 2026-06-25 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_add_composite_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, help_text='Calories burned (cap 20000 — sanity bound, ultra-endurance worst case).', null=True, validators=[django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, help_text='Workout duration in minutes (1-1440).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='perceived_exertion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 RPE', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
