# Generated by Django 5.0.6 on 2026-06-12 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('reminder_type', models.CharField(choices=[('workout', 'Workout'), ('water', 'Water'), ('meal', 'Meal'), ('measurement', 'Measurement'), ('custom', 'Custom')], default='workout', max_length=20)),
                ('time_of_day', models.TimeField()),
                ('days_of_week', models.JSONField(default=list, help_text='List of 3-letter weekday codes: mon, tue, wed, thu, fri, sat, sun.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_of_day'],
            },
        ),
    ]
