# Generated by Django 5.0.6 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['order', 'time_of_day']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
