# Generated by Django 5.0.6 on 2026-06-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_options_reminder_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['order', 'time_of_day', 'start_time']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Last allowed trigger time for interval reminders.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes between triggers (e.g. 60 = every hour).', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Once per day'), ('interval', 'Repeat throughout the day')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='start_time',
            field=models.TimeField(blank=True, help_text='First trigger of the day for interval reminders.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='days_of_week',
            field=models.JSONField(default=list, help_text='3-letter weekday codes. Empty list = every day.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('workout', 'Workout'), ('water', 'Water / Hydration'), ('meal', 'Meal / Nutrition'), ('measurement', 'Measurement'), ('movement', 'Movement / Stretch'), ('custom', 'Custom')], default='workout', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='Trigger time for once-per-day reminders.', null=True),
        ),
    ]
