# Generated by Django 5.0.6 on 2026-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('balance', 'Balance')], max_length=20)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('core', 'Core'), ('quads', 'Quadriceps'), ('hamstrings', 'Hamstrings'), ('glutes', 'Glutes'), ('calves', 'Calves'), ('full_body', 'Full body'), ('cardio', 'Cardio')], max_length=20)),
                ('secondary_muscles', models.JSONField(blank=True, default=list)),
                ('equipment', models.CharField(choices=[('bodyweight', 'Bodyweight'), ('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('kettlebell', 'Kettlebell'), ('machine', 'Machine'), ('cable', 'Cable'), ('band', 'Resistance band'), ('cardio', 'Cardio equipment'), ('other', 'Other')], default='bodyweight', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('is_compound', models.BooleanField(default=False)),
                ('met_value', models.DecimalField(decimal_places=2, default=4.0, help_text='MET value for cardio calorie estimation.', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
