# Generated by Django 5.0.6 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tutorial_url',
            field=models.URLField(blank=True, help_text='Optional link to a curated tutorial video (YouTube or other). If empty, the app generates a YouTube search URL automatically.'),
        ),
    ]
